package com.appcues.analytics

/**
 * Provides a method to listen for analytics published by the SDK.
 */
interface AnalyticsListener {

    /**
     * Represents the different types of analytics published by the SDK.
     */
    enum class AnalyticType {
        IDENTIFY, GROUP, EVENT, SCREEN
    }

    /**
     * Notifies the listener when Appcues analytics tracking occurs.
     *
     * [type] The type of the analytic.
     * [value] Contains the primary value of the analytic being tracked. For events - the event name,
     * for screens - the screen title, for identify - the userId, for group - the groupId
     * [properties] Optional properties that provide additional context about the analytic.
     * [isInternal] True, if the analytic was internally generated by the SDK, as opposed to passed in from the host application.
     * For example, flow or session analytics are internal.
     */
    fun trackedAnalytic(type: AnalyticType, value: String?, properties: Map<String, Any>?, isInternal: Boolean)
}
