package com.appcues.di

import com.appcues.AppcuesConfig
import org.koin.dsl.ScopeDSL

/**
 * Implement this interface to define a module that will be loaded for each new Appcues scope
 *
 * Used at AppcuesKoinContext
 */
internal interface KoinScopePlugin {

    /**
     * Used to load new scoped factories into [koinScope]
     *
     * [koinScope] ScopeDSL generated by [AppcuesKoinContext]
     * [config] AppcuesConfig for this session
     *
     * usage:
     *  override fun installIn(koinScope: ScopeDSL, config: AppcuesConfig) {
     *      with(koinScope) {
     *           scoped { Any() }
     *      }
     *  }
     */
    fun installIn(koinScope: ScopeDSL, config: AppcuesConfig)
}
