default_platform(:android)

platform :android do

  desc "Validate the code in the SDK repo works properly"
  lane :validate_code do
    gradle(task: 'detekt')
    gradle(task: ':appcues:build')
    gradle(task: ':samples:kotlin-android-app:bundleRelease')
  end

  desc "Generate unit test code coverage report"
  lane :code_coverage do
    gradle(task: ':appcues:debugUnitTestCoverage')
  end

  desc "Deploy a new version to Google Play internal test"
  lane :deploy_sample do
    sh("sh", "./replace-placeholders.sh", "kotlin-android-app", ENV["EX_APPCUES_ACCOUNT_ID"], ENV["EX_APPCUES_APPLICATION_ID"])
    gradle(task: ':samples:kotlin-android-app:versionTxt')
    gradle(task: ':samples:kotlin-android-app:bundleRelease')

    sample_version=File.read("../sample_version.txt")

    git_log = changelog_from_git_commits(
      commits_count: 5,
      pretty: "- [%as] %s"
    )
    changelog_message = "Version #{sample_version}\n\nLatest commits on #{ENV["CIRCLE_BRANCH"]}:\n" + git_log
    truncated_changelog = changelog_message.truncate(500) # Google play API limit
    
    # metadata dir is how What's New text gets communicated 
    # https://docs.fastlane.tools/actions/supply/#changelogs-whats-new
    metadata_dir = "./metadata/android/en-US/changelogs"
    default_changelog = metadata_dir + "/default.txt"
    version_changelog = metadata_dir + "/#{ENV["CIRCLE_BUILD_NUM"]}.txt"
    sh("mkdir", "-p", metadata_dir)
    sh("echo 'Version #{sample_version}' > #{default_changelog}")
    sh("echo '#{truncated_changelog}' > #{version_changelog}")

    upload_to_play_store(
      track: 'internal', 
      skip_upload_apk: true, 
      json_key_data: ENV["PLAY_STORE_API_KEY"],
      rollout: '1'
    )    
  end
end
