default_platform(:android)

platform :android do

  desc "Validate the code in the SDK repo works properly"
  lane :validate_code do
    gradle(task: 'detekt')
    gradle(task: ':appcues:build')
    gradle(task: ':samples:kotlin-android-app:bundleRelease')
  end

  desc "Generate unit test code coverage report"
  lane :code_coverage do
    gradle(task: ':appcues:debugUnitTestCoverage')
  end

  desc "Deploy a new version to Google Play internal test"
  lane :deploy_sample do
    sh("sh", "./replace-placeholders.sh", "kotlin-android-app", ENV["EX_APPCUES_ACCOUNT_ID"], ENV["EX_APPCUES_APPLICATION_ID"])
    
    keystorePath = File.join(Dir.pwd, "..", "appcues.keystore")
    sample_version = "1.0.0-#{ENV["CIRCLE_BUILD_NUM"]}"

    gradle(
      task: 'bundle',
      build_type: 'Release',
      project_dir: 'samples/kotlin-android-app',
      gradle_path: '../../gradlew',
      print_command: true,
      properties: {
        "android.injected.signing.store.file" => keystorePath,
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEYSTORE_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.version.code" => ENV["CIRCLE_BUILD_NUM"].to_i,
        "android.injected.version.name" => sample_version,
      }
    )

    git_log = changelog_from_git_commits(
      commits_count: 5,
      pretty: "- [%as] %s"
    )
    changelog_message = "Version #{sample_version}\n\nLatest commits on #{ENV["CIRCLE_BRANCH"]}:\n" + git_log
    
    # metadata dir is how What's New text gets communicated 
    # https://docs.fastlane.tools/actions/supply/#changelogs-whats-new
    metadata_dir = "./metadata/android/en-US/changelogs"
    default_changelog = metadata_dir + "/default.txt"
    version_changelog = metadata_dir + "/#{ENV["CIRCLE_BUILD_NUM"]}.txt"
    sh("mkdir", "-p", metadata_dir)
    sh("echo 'Version #{sample_version}' > #{default_changelog}")
    sh("echo '#{changelog_message}' > #{version_changelog}")

    upload_to_play_store(
      track: 'internal', 
      skip_upload_apk: true, 
      json_key_data: ENV["PLAY_STORE_API_KEY"],
      rollout: '1'
    )    
  end
end
